### ISSUE TITLE
Missing credentials in app (version 0.2.24)

### ISSUE THREAD

**Issue by cdegallaix** [DinoChiesa/apigee-edge-js#1]
Hello,

First, a big thank you for creating and maintaining this library! 

We have an issue with the last version (0.2.24), the 'credentials' property is missing in the app. We don't have any issue with version 0.2.22.

Here is a piece of the code that we use (simplified for readability): 

```
const getApp = function getApp(org, developerEmail, partner) {
  const name = createApigeeAppNameForPartner(partner);

  const options = {
    developerEmail,
    appName: name,
  };

  return org.developerapps.getAsync(options);
};

getApp(org, apigeeDeveloper.email, partner, true)
   .then(app => app.credentials[0].consumerKey); // Cannot read property '0' of undefined
```

Could you have a look?

Thank you!

**Comment by DinoChiesa** [comment]
Hmmm!  I don't have a developerapps.getAsync() method. 
Maybe you've modified it? 
And I get credentials back, still., in v0.2.27.
