### ISSUE TITLE
Can I use this library with Angular 8 and Nodejs 12

### ISSUE THREAD

**Issue by varuntit101** [DinoChiesa/apigee-edge-js#10]
I am trying to create devportal with Angular 8 and Nodejs 12, Can I use this library with the mentioned versions. 

While integrating, I am facing these errors : 
`
WARNING in ./node_modules/apigee-edge-js/lib/edge.js 80:39-63    
Critical dependency: the request of a dependency is an expression
ERROR in ./node_modules/readline-sync/lib/readline-sync.js       
Module not found: Error: Can't resolve 'child_process' in 'G:\Angular\-app02\node_modules\readline-sync\lib'
ERROR in ./node_modules/apigee-edge-js/lib/tokenMgmt.js
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\apigee-edge-js\lib'
ERROR in ./node_modules/apigee-edge-js/lib/keystore.js
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\apigee-edge-js\lib'
ERROR in ./node_modules/apigee-edge-js/lib/reference.js
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\apigee-edge-js\lib'
ERROR in ./node_modules/apigee-edge-js/lib/resourcefile.js       
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\apigee-edge-js\lib'
ERROR in ./node_modules/apigee-edge-js/lib/spec.js
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\apigee-edge-js\lib'
ERROR in ./node_modules/apigee-edge-js/lib/deployableAsset.js    
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\apigee-edge-js\lib'
ERROR in ./node_modules/apigee-edge-js/node_modules/adm-zip/util/fileSystem.js
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\apigee-edge-js\node_modules\adm-zip\util'     
ERROR in ./node_modules/archiver/lib/core.js
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\archiver\lib'
ERROR in ./node_modules/fs.realpath/index.js
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\fs.realpath'
ERROR in ./node_modules/fs.realpath/old.js
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\fs.realpath'
ERROR in ./node_modules/glob/glob.js
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\glob'
ERROR in ./node_modules/glob/sync.js
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\glob'
ERROR in ./node_modules/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\graceful-fs'
ERROR in ./node_modules/netrc/index.js
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\netrc'
ERROR in ./node_modules/original-fs/index.js
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\original-fs'
ERROR in ./node_modules/readline-sync/lib/readline-sync.js       
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\readline-sync\lib'
ERROR in ./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in 'G:\Angular\-app02\node_modules\request\lib'
`

If anyone can help with this, that will be very helpful.

Thanks

**Comment by DinoChiesa** [comment]
Hi Varun
thanks for the note.

I implemented this library without imagining that someone would want to use it within a browser sandbox.  The library stashes tokens in the filesystem with the fs module. And the library asks for credentials from the commandline using the readline module.  I think the dependency on those things, at a minimum, will prevent the library from being usable within a browser . 

It might be possible to refactor the library to extract those things; or to produce a different package that excludes those things.  But that's a task I cannot sign up to.  I'd guess that it would involve a lot of research by me, a lot of coding work, and some extensive testing, and I don't have the free time to do that volunteer work.

If you were to do that work or you and some other people were able to collaborate and do that work, then I'd be willing to review the pull request. 

Sorry I don't have better news. Good luck.

**Comment by varuntit101** [comment]
Hi Dino,

Thanks for replying so quickly and pointing out the dependencies. I will see what can I do and can collaborate some other people to help me on this. I will create a pull request if I will have any success.

Thanks,
Varun

**Comment by hsnbilgen** [comment]
Hi Guys,

I think this library as expected to use from client side cli to be called. Even I see very usefull and needed these CLI cmds for CI/CD pipelines while we already build our own. Thanks @DinoChiesa appreciate that.

Maybe addition to main question of this issue move this lib into API usage and exposable APIs for client application usage either not really needed because APIGEE already exposed these apis free of charge there is a possible way to do that APIGEE Management APIs can be used from client applicaiton either if needed possible can be found somewhere in github or APIGEE docs as POSTMAN colleciton

Thanks
HS
