### ISSUE TITLE
Issue when using on mfa enable org

### ISSUE THREAD

**Issue by echbremmer** [DinoChiesa/apigee-edge-js#14]
Hi,

I am trying to use the library with mfa enabled on the apigee management api and I get following error:

[2020-Nov-20 18:27:49] found no stashed token.
[2020-Nov-20 18:27:49] POST https://login.apigee.com/oauth/token
[2020-Nov-20 18:27:49] status: 401
[2020-Nov-20 18:27:49] result: {"error":"unauthorized","error_description":"Error: Invalid MFA code."}
[2020-Nov-20 18:27:49] POST error: bad status: 401

Since I'm never prompted for an mfa code this makes sense but I cannot figure out where to provide it or how to get prompted for it. An obvious place is in the options of the connect function as 'mfa_code' but the function that generates the oath endpoint simply lacks the mfa_token query param:  

https://github.com/DinoChiesa/apigee-edge-js/blob/76279170248ba0fc90825dbe52a0ceb69a065902/lib/connection.js#L53

In addition I believe there to be a bug here (and next line) that prevents the value of mfa_code to be passed from connection options in the first place:

https://github.com/DinoChiesa/apigee-edge-js/blob/76279170248ba0fc90825dbe52a0ceb69a065902/lib/connection.js#L215

This code references arg1.mfa_token instead of arg1.mfa_code so it doesn't get passed to invokeLegacyApigeeTokenEndpoint.

Based on above understanding I fixed this on my local machine. I would be happy to do a pull request if above is indeed correct. I also think this would help other people as I cannot imagine I'm the only one that is affected.

Regards,
Emile Bremmer

**Comment by echbremmer** [comment]
After additonal analysis it appears that the mfa token van also be provided to the auth endpoint as a form parameter. Since that is better (and perhaps the originally intended approach in this library) the fix could be to rename 'mfa_code' in edge.js to 'mfa_token'.

**Comment by DinoChiesa** [comment]
This is now fixed.
