### ISSUE TITLE
Refresh token expiry 

### ISSUE THREAD

**Issue by bialesdaniel** [DinoChiesa/apigee-edge-js#2]
I was going to do a PR to expose the tokenMgmt module. I was thinking it would be beneficial to be able to tell if the refresh token had expired cause it would be useful to know if you can just use the refresh token or need a whole new token. If I recall the refresh token is valid for 24 hrs after issuing the access_token. Does adding that functionality make sense? If so I can submit a PR

**Comment by DinoChiesa** [comment]
Hi Daniel.
Sorry your message has been neglected for so long. 
I don't recall the lifetime of the refresh token, but 24hr sounds correct. 
re: "if you can just use the refresh token or need a whole new token"
When the library uses the refresh_token to get a new access_token, it also gets a new refresh_token. 

In the case that the existing, cached refresh_token is expired, then... the tokenMgmt library also resorts to the username/password to get a new token.  

So I think it does what is necessary now. 
If I'm wrong let me know.
