### ISSUE TITLE
Management of target servers

### ISSUE THREAD

**Issue by trickleup** [DinoChiesa/apigee-edge-js#3]
Is the management of target servers supported in this library?

Best,
Johan

**Comment by DinoChiesa** [comment]
Hi, I just implemented a capability to create, update, enable, disable, or delete targetservers in an environment. See what you think.  It's in the master branch, not yet released.

**Comment by trickleup** [comment]
That was fast! :)

It looks good to me at first glance, and I'm happy to try it out as soon as it is on npm.

**Comment by DinoChiesa** [comment]
ok, great!  Should be available now in v0.4.7
