### ISSUE TITLE
Setup of Proxy

### ISSUE THREAD

**Issue by Dingenis** [DinoChiesa/apigee-edge-js#5]
Hi,

Is it possible to use a proxy? This is something that is needed when working from a coporate environment.

Cheers,

Bram

**Comment by DinoChiesa** [comment]
Hi Bram,  I guess you're referring to using an HTTP proxy to handle requests.
The library uses requestjs, so you can specify the proxy you would like to use in an environment variable. 
details here: https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables
Let me know if this addresses your issue.

**Comment by Dingenis** [comment]
Hi Dino,

Sorry proxy is indeed a bit unclear 😅  Yes that is exatcly what I meant, I will check it out next thing tomorrow when I am work. Thanks!

Cheers

**Comment by Dingenis** [comment]
Hi Dino,

When setting the environment variable HTTP_PROXY and HTTPS_PROXY it works like a charm, thanks!

Cheers,

Bram
